channels:
  - kberryUSGS
  - usgs-astrogeology
  - conda-forge
  - defaults

dependencies:
  - ale >=0.7.1
  - boost
  - armadillo
  - blas
  - bullet=2.86.1=0 # source code changes in our version
  - bz2file
  - bzip2
  - cmake >=3.15
  - cspice
  - curl
  - doxygen
  - eigen
  - embree
  - geos>=3.7,<3.8
  - geotiff
  - gmm
  - gmp
  - gsl
  - hdf5
  - icu
  - jama
  - jpeg
  - kakadu==1
  - krb5
  - libpng>=1.6.34
  - libprotobuf=3.9.1
  - libtiff
  - libxml2
  - make
  - mesalib
  - mysql
  - mysql-connector-c
  - nanoflann
  - nlohmann_json
  - ninja==1.7.2
  - conda-forge/label/gcc7::nn
  - opencv=3.4.7#>=3.3.0,<4.0.0#do we need this dependency? or only libopencv
  - libopencv=3.4.7#how to pin to opencv
  - openssl
  - pcl
  - protobuf=3.9.1
  - qhull
  - kberryusgs::qt=5.12.5
  - qwt
  - sqlite
  - suitesparse
  - superlu
  - tnt
  - x264#=20131218
  - xalan-c
  - xerces-c
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxi
  - zlib
